### ISSUE TITLE
getting an unexpected keyword argument error in seqspec init

### ISSUE THREAD

**Issue by bdoughty** [pachterlab/seqspec#43]
I am trying to follow the tutorial here (https://github.com/pachterlab/seqspec/blob/main/docs/TUTORIAL.md) and am running into an issue. I have installed seqspec via pip (seqspec 0.2.0) and and running the command exactly from the tutorial `seqspec init -n SPLiTSeq -m 1 -o spec.yaml "((P5:29,Spacer:8,Read_1_primer:33,cDNA:1098,RT_primer:15,Round_1_BC:8,linker_1:30,Round_2_BC:8,Linker_2:30,Round_3_BC:8,UMI:10,Read_2_primer:22,Round_4_BC:6,P7:24)rna)"`. I am getting the error:
`
Traceback (most recent call last):
  File "/oak/stanford/groups/wjg/bgrd/bin/miniconda3/envs/IGVF_utils/bin/seqspec", line 8, in <module>
    sys.exit(main())
  File "/oak/stanford/groups/wjg/bgrd/bin/miniconda3/envs/IGVF_utils/lib/python3.8/site-packages/seqspec/main.py", line 82, in main
    COMMAND_TO_FUNCTION[sys.argv[1]](parser, args)
  File "/oak/stanford/groups/wjg/bgrd/bin/miniconda3/envs/IGVF_utils/lib/python3.8/site-packages/seqspec/seqspec_init.py", line 53, in validate_init_args
    spec = run_init(name, tree[0].descendants)
  File "/oak/stanford/groups/wjg/bgrd/bin/miniconda3/envs/IGVF_utils/lib/python3.8/site-packages/seqspec/seqspec_init.py", line 70, in run_init
    assay = Assay(
TypeError: __init__() got an unexpected keyword argument 'assay'
`

**Comment by sbooeshaghi** [comment]
Can you try installing from devel?

pip install git+https://github.com/pachterlab/seqspec@devel

**Comment by bdoughty** [comment]
Ok, that worked! Thanks!
