### ISSUE TITLE
seqspec split error

### ISSUE THREAD

**Issue by RaiRuhi** [pachterlab/seqspec#48]
**seqspec split -o split spec.yaml**

Traceback (most recent call last):
  File "/software/miniconda3/bin/seqspec", line 8, in <module>
    sys.exit(main())
  File "/software/miniconda3/lib/python3.9/site-packages/seqspec/main.py", line 82, in main
    COMMAND_TO_FUNCTION[sys.argv[1]](parser, args)
  File "/software/miniconda3/lib/python3.9/site-packages/seqspec/seqspec_split.py", line 35, in validate_split_args
    spec.sequencer,
AttributeError: 'Assay' object has no attribute 'sequencer'

_I commented out the spec.assay in seqspec_split.py and now I am getting_

Traceback (most recent call last):
  File "/software/miniconda3/bin/seqspec", line 8, in <module>
    sys.exit(main())
  File "/software/miniconda3/lib/python3.9/site-packages/seqspec/main.py", line 82, in main
    COMMAND_TO_FUNCTION[sys.argv[1]](parser, args)
  File "/software/miniconda3/lib/python3.9/site-packages/seqspec/seqspec_split.py", line 33, in validate_split_args
    spec_m = Assay(
TypeError: __init__() missing 5 required positional arguments: 'sequence_kit', 'library_protocol', 'library_kit', 'sequence_spec', and 'library_spec'

**Comment by sbooeshaghi** [comment]
The error was arising from not having updated the Assay initialization with the enhanced version of the seqspec for each "split". I have corrected this and have pushed the corrected code to the repo. `seqspec split` should now work as expected. You can try it out with the `dogmaseq-dig` spec located in `examples/specs/dogmaseq-dig/spec.yaml`

```bash
$ seqspec split -o split spec.yaml
$ ls -1
spec.yaml
split.atac.yaml
split.protein.yaml
split.rna.yaml
split.tag.yaml
```
